Template Protocol
=================
Garrett D'Amore <garrett@damore.org>
v 0.2, 2017-08-01

image:https://img.shields.io/badge/status-draft-yellow.svg[draft]

Template Protocol
-----------------

* Status: draft
* Authors: Garrett D'Amore <garrett@damore.org>
* Version: 0.2

Abstract
--------

This is a template protocol that describes an SP protocol.
There is no such protocol, this document serves only to act as a starting
point.  Please replace this with an abstract.

License
-------

Copyright (c) 2017 The Authors.

This specification is licensed under the Apache License, Version 2.0
(the "License");  you may not use this file except in compliance with the
License.
You may obtain a copy of the license
http://www.apache.org/licenses/LICENSE-2.0[online].

Language
--------

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be
interpreted as described in https://tools.ietf.org/html/rfc2119[RFC 2119].

Goals
-----

The goal of this document is to serve as a template to RFC authors.

Versioning
----------

RFCs use a version number based on two decimal integer values separated
by a decimal point, as in _major_._minor_.  The _major_ value is the
primary version of the specification.  This number is incremented whenever
a normative change is made to the specification.
The _minor_ value is incremented only when non-normative changes, such
as clarifications and error corrections are made to existing specifications.
When a new _major_ number is assigned, the _minor_ number will be reset to
zero.

Note that the _major_ and _minor_ number are each whole numbers, and the
total version should not be treated as a rational number.  This means that
a version of `1.10` would represent the 10th revision to version 1, and
is newer than version `1.9`.  This also means that a version of `1.01` is
non-sensical, and would never be used.

Document Format
---------------

This document is in http://asciidoc.org[AsciiDoc] format, and authors
may use the full markup syntax.

Subheader
~~~~~~~~~

A sub-header subsection.

Sub-Subheader
^^^^^^^^^^^^

An even more nested header. (This is a level 3 header.)

Definition List
^^^^^^^^^^^^^^^

term one::
	The definition of term one is ....
term two::
	A second termi

Tables
^^^^^^

[width="20%, options="header"]
|===
|A|B|C
|1|2|3
|2|3|4
|5 2+|6 spans two columns
|===

Code
^^^^

First generic preformatted:
----
 int main(int argc, char **);
----

Then as C:
[source, c]
----
   int main(int argc, char **argv);
----

Diagrams
^^^^^^^^

Diagrams use http://ditaa.sourceforge.net/[ditaa] syntax.


[ditaa]
----

 +-------------+
 | Protocol ID |
 +-------------+

 +-------+   +-----+
 | Start |-->| End |
 +-------+   +-----+
----

